version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgresql_user:GsDsXXIECaHl6oOiWNKMIPKIxGCkRpay@dpg-d178cbndiees73dtodng-a.oregon-postgres.render.com/postgresql_crud_db
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgresql_user
      POSTGRES_PASSWORD: GsDsXXIECaHl6oOiWNKMIPKIxGCkRpay
      POSTGRES_DB: postgresql_crud_db
    ports:
      - "5432:5432"
